In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df_population = pd.read_excel('data-files/population-in-seoul.xlsx', header=1)
# df_population.drop(df_population.columns[0], axis=1).drop(0, axis=0) # (합계 컬럼, 총계 행 제거)
df_population = df_population.iloc[1:, 1:] # drop과 같은 효과 발생 (합계 컬럼, 총계 행 제거)
df_population = df_population.drop(df_population.columns[1:5], axis=1) #  (2024 년이 중복되어서 제거)

new_columns = ["자치구"] # 첫 번째 컬럼명
for year in np.arange(2014, 2025):
    new_columns.append(f"{year}-인구수")
    new_columns.append(f"{year}-한국인")
    new_columns.append(f"{year}-외국인")
    new_columns.append(f"{year}-고령자")
    # new_columns += [f"{year}-{c}" for c in ['인구수', '한국인', '외국인', '고령자']]

df_population.columns = new_columns # 전체 컬럼명을 모두 변경

df_population.reset_index(drop=True, inplace=True)
df_population

C:\Users\human\AppData\Roaming\Python\Python311\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,자치구,2014-인구수,2014-한국인,2014-외국인,2014-고령자,2015-인구수,2015-한국인,2015-외국인,2015-고령자,2016-인구수,...,2022-외국인,2022-고령자,2023-인구수,2023-한국인,2023-외국인,2023-고령자,2024-인구수,2024-한국인,2024-외국인,2024-고령자
0,종로구,165344,156993,8351,24537,163822,154986,8836,24892,161922,...,10832,27958,150453,139417,11036,28764,149608,138336,11272,29840
1,중구,136227,128065,8162,19960,134329,125733,8596,20302,134409,...,10348,25055,131793,121312,10481,25920,131214,120544,10670,26853
2,용산구,249914,235951,13963,34896,247909,233342,14567,35715,245102,...,14634,39037,227106,213151,13955,39747,217194,203854,13340,39407
3,성동구,303891,296086,7805,36684,305065,297003,8062,38164,307161,...,7234,47720,284766,277361,7405,49462,281289,273669,7620,51245
4,광진구,377375,363354,14021,38974,375180,360369,14811,40368,372104,...,13836,54071,351180,335554,15626,56819,348652,331963,16689,59743
5,동대문구,376319,363687,12632,50915,373824,360153,13671,52490,370312,...,16957,64468,359873,341149,18724,67030,358603,338735,19868,69582
6,중랑구,423411,418836,4575,51995,418620,413909,4711,54095,415677,...,4822,74920,387470,382155,5315,78955,385349,379274,6075,83492
7,성북구,475961,466706,9255,62066,469560,459275,10285,63281,461617,...,11587,77475,438168,425602,12566,80414,435037,421560,13477,83568
8,강북구,338410,335025,3385,50841,334426,330873,3553,52598,330704,...,4042,66307,292977,288113,4864,68617,289374,283597,5777,71411
9,도봉구,355712,353709,2003,46471,353241,351242,1999,48590,350272,...,2295,66998,309494,306948,2546,70436,306032,303228,2804,74223
10,노원구,586056,582552,3504,66480,578221,574583,3638,68909,571212,...,4280,92040,502925,498213,4712,96422,496552,491247,5305,100579
11,은평구,503243,498644,4599,67002,502578,497920,4658,69753,495937,...,3856,89650,470869,466770,4099,93817,465350,460919,4431,98063
12,서대문구,320861,310376,10485,45309,323105,312141,10964,46758,325871,...,13217,55996,320629,306231,14398,58113,318622,302853,15769,60229
13,마포구,395830,385439,10391,47360,398351,387643,10708,48598,390887,...,10947,55914,375162,363697,11465,57895,372745,361417,11328,60009
14,양천구,490708,486221,4487,48175,489010,484532,4478,50398,481845,...,3129,72393,439252,436028,3224,76317,434351,430976,3375,80390
15,강서구,591653,585160,6493,64287,595691,589074,6617,67950,602104,...,5472,97128,568826,563058,5768,102096,562194,556171,6023,107553
16,구로구,457131,425831,31300,51187,454604,422092,32512,53719,449600,...,23103,75890,415651,392405,23246,79984,411916,388169,23747,83873
17,금천구,258030,238463,19567,29553,256167,236284,19883,31070,254654,...,13176,42928,241105,227481,13624,45342,239070,225159,13911,47951
18,영등포구,421436,382352,39084,49829,417811,378504,39307,51481,406779,...,22410,64810,397800,374794,23006,67509,397173,373773,23400,70455
19,동작구,419261,407470,11791,52327,412774,400641,12133,53610,413247,...,9836,68231,389714,378769,10945,70474,387352,375799,11553,73201
20,관악구,531960,513186,18774,62577,529031,509663,19368,64985,525607,...,14474,82447,497883,481956,15927,85418,495620,477812,17808,88885
21,서초구,454288,449678,4610,47469,451258,446764,4494,49280,451477,...,4126,62347,412078,407664,4414,65661,413076,408376,4700,68735
22,강남구,583446,578114,5332,57444,581760,576495,5265,60330,572140,...,5001,81715,550282,544873,5409,86606,563215,557345,5870,91470
23,송파구,671794,664738,7056,65025,667480,660302,7178,68292,664946,...,5713,103573,660025,654166,5859,108894,656310,650110,6200,114243
24,강동구,481332,476597,4735,50253,463321,458658,4663,51935,448471,...,3970,78340,463318,459167,4151,82984,481474,476942,4532,89895

In [23]:
# 2024년도 데이터만 추출
df_population_2024 = df_population.iloc[:, [0,-4,-3,-2,-1]].copy()
df_population_2024.head(3)

   자치구  2024-인구수  2024-한국인  2024-외국인  2024-고령자
0  종로구    149608    138336     11272     29840
1   중구    131214    120544     10670     26853
2  용산구    217194    203854     13340     39407

In [24]:
# 2024년 데이터에 외국인 비율 컬럼과 고령자 비율 컬럼 추가
df_population_2024['외국인비율'] = df_population_2024['2024-외국인'] / df_population_2024['2024-인구수']
df_population_2024['고령자비율'] = df_population_2024['2024-고령자'] / df_population_2024['2024-인구수']
df_population_2024.head()

   자치구  2024-인구수  2024-한국인  2024-외국인  2024-고령자     외국인비율     고령자비율
0  종로구    149608    138336     11272     29840  0.075344  0.199455
1   중구    131214    120544     10670     26853  0.081318  0.204650
2  용산구    217194    203854     13340     39407  0.061420  0.181437
3  성동구    281289    273669      7620     51245  0.027090  0.182179
4  광진구    348652    331963     16689     59743  0.047867  0.171354

In [26]:
# 외국인 비율 높은 자치구 / 고령자 비율 높은 자치구 조회
df_population_2024.sort_values(by="고령자비율", ascending=False)
df_population_2024.sort_values(by="외국인비율", ascending=False)

     자치구  2024-인구수  2024-한국인  2024-외국인  2024-고령자     외국인비율     고령자비율
1     중구    131214    120544     10670     26853  0.081318  0.204650
0    종로구    149608    138336     11272     29840  0.075344  0.199455
2    용산구    217194    203854     13340     39407  0.061420  0.181437
18  영등포구    397173    373773     23400     70455  0.058916  0.177391
17   금천구    239070    225159     13911     47951  0.058188  0.200573
16   구로구    411916    388169     23747     83873  0.057650  0.203617
5   동대문구    358603    338735     19868     69582  0.055404  0.194036
12  서대문구    318622    302853     15769     60229  0.049491  0.189030
4    광진구    348652    331963     16689     59743  0.047867  0.171354
20   관악구    495620    477812     17808     88885  0.035931  0.179341
7    성북구    435037    421560     13477     83568  0.030979  0.192094
13   마포구    372745    361417     11328     60009  0.030391  0.160992
19   동작구    387352    375799     11553     73201  0.029826  0.188978
3    성동구    281289    273669      7620     51245  0.027090  0.182179
8    강북구    289374    283597      5777     71411  0.019964  0.246778
6    중랑구    385349    379274      6075     83492  0.015765  0.216666
21   서초구    413076    408376      4700     68735  0.011378  0.166398
15   강서구    562194    556171      6023    107553  0.010713  0.191309
10   노원구    496552    491247      5305    100579  0.010684  0.202555
22   강남구    563215    557345      5870     91470  0.010422  0.162407
11   은평구    465350    460919      4431     98063  0.009522  0.210730
23   송파구    656310    650110      6200    114243  0.009447  0.174069
24   강동구    481474    476942      4532     89895  0.009413  0.186708
9    도봉구    306032    303228      2804     74223  0.009162  0.242533
14   양천구    434351    430976      3375     80390  0.007770  0.185081

In [27]:
df_population.to_csv('data-files/population-in-seoul-2.csv', index=False)
df_population_2024.to_csv('data-files/population-in-seoul-2024.csv', index=False)